default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: soccer_chatbot_development

test:
  <<: *default
  database: soccer_chatbot_test

production:
  <<: *default
  database: soccer_chatbot_production
